CREATE TABLE `events` (
	`id` text PRIMARY KEY NOT NULL,
	`eventId` text,
	`title` text,
	`description` text,
	`socialIssue` text,
	`status` text,
	`lastChange` text,
	`date` text,
	`dateISO` text,
	`shortDate` text,
	`startTime` text,
	`endTime` text,
	`weekDay` integer,
	`weekDayName` text,
	`topic` text,
	`topic2` text,
	`category` text,
	`eventType` text,
	`location` text,
	`organizer` text,
	`persons` text,
	`contactPerson1` text,
	`contactPerson2` text,
	`url` text,
	`uri` text,
	`urls` text,
	`digitalStream` text,
	`digitalStreamUrl` text,
	`digitalArchiveUrl` text,
	`digitalMeeting` text,
	`color` text,
	`showEmail` text,
	`showPhone` text,
	`languages` text,
	`accessibility` text,
	`environmental` text,
	`interactiveLink` text,
	`interactiveLinkDescription` text,
	`streamService` text
);
--> statement-breakpoint
DROP TABLE `document_chunks`;--> statement-breakpoint
DROP TABLE `documents`;